<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 10 Aug 2024 14:16:38 +0000
 */
$conf['title'] = 'Default';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
// ACL is mandatory (it was just created for backward compat)
$conf['useacl'] = 1;
// The admin user group
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
// Sane Default
// The level 2 is the top of TOC rendering
// https://www.dokuwiki.org/config:toptoclevel
$conf['toptoclevel'] = 2;
// Number of heading for rendering
// https://www.dokuwiki.org/config:tocminheads
$conf['tocminheads'] = 1;
// Maximum section editing level
// https://www.dokuwiki.org/config:maxseclevel
$conf['maxseclevel'] = 4;
// https://www.dokuwiki.org/config:useheading
$conf['useheading'] = 1;
